### PR TITLE
Document the project

### LINKED ISSUE #19: Create a README file
Create a basic README file with a concise description of the project.

### PR DESCRIPTION
**Pull request by Musigwa**
**Description:**

This PR Creates the README.md and Updates the SECURITY.md file.

**Why this PR?**

This is necessary for the basic documentation of what the project is about and giving the instructions on setting up the environment for the new developers.

**Which issue does it resolve**

Resolves #19 

**Dev Notes:**

Please note the preferred branch naming convention that we can adopt from now on:

- **For a feature:**

```bash
feat#42/{short-description}
```

- **For a bug fix:**

```bash
fix#23/{short-description}
```

- **For documentation:**

```bash
doc#23/{short-description}
```

- **For configuration chores:**

```bash
config#23/{short-description}
```

**NB:** 
> The number following the issue type prefix is the issue ID number on the repository's open issues list. The one you're resolving for.

`Example: doc#19/create-readme-file
`

### CODE REVIEW

**Review by Nziranziza — APPROVED** [review]
@Musigwa this looks great

**Comment by Musigwa** [comment]
> @Musigwa this looks great

Thanks, @Nziranziza, that was the least I can do.

**Review by pierratono — APPROVED** [review]
LGTM

**Review by Nziranziza — APPROVED** [review]
@Musigwa I am approving but I do have a suggest, this PR description has some important information which I think deserve to be under readme or wiki. I mean git workflow and PR, branch and commit conventions

**Comment by Musigwa** [comment]
> @Musigwa I am approving but I do have a suggest, this PR description has some important information which I think deserve to be under readme or wiki. I mean git workflow and PR, branch and commit conventions

Sure @Nziranziza we need to have a WIKI for team conventions. I'm opening an issue for that and I will assign it to one of us. Thanks for the suggestions.

**Pull request closed without merging**
